horde:
  # Delay between horde spawns in minutes
  interval: 120
  # Mobs spawned in horde will despawn after this amount of time
  duration: 60
  # Spawn settings
  spawn:
    # Min/max amount of mobs to spawn per horde
    amount:
        min: 2
        max: 4
    # How many groups
    groups: 25
    # World to spawn horde in
    world: world # Defaults to the first world in the server
    # Coordinates to spawn horde at
    coordinates:
      x: -186.0
      y: 88.0
      z: 495.0
    # Radius to spawn horde in
    radius: 150
  messages:
    # Message sent to players when a horde spawns
    spawn: "&c&lA horde has spawned in the warzone!"
    # Message sent to players when they kill a horde member
    # {souls} = Souls gained, {total} = Total souls
    kill: "&cYou have slain a horde member and gained {souls} soul!\n&cYou now have {total} souls!"

telepathy:
  # Message sent to killer when they kill a player with Telepathy enchant
  # {m} = Minutes, {x} = X, {y} = Y, {z} = Z
  message: "&cChest placed at X: {x}, Y: {y}, Z: {z} for &4{m} minutes!"
  # Duration of chest in minutes
  chest-duration: 5

timber:
  # Amount of logs to break per enchant level.
  # amount-per-level * enchant-level = amount of logs broken
  amount-per-level: 5

shotgun:
  # Cooldown between shotgun shots in seconds
  cooldown: 1
  # Initial angle between shotgun shots in degrees
  initial-angle: 10
  # Angle subtracted from initial angle per shot in degrees based on enchant level
  # initial-angle - (angle-per-level * enchant-level) = angle between shots
  angle-per-level: 5
  # Initial number of arrows fired
  initial-arrows: 5
  # Number of arrows added per enchant level
  # initial-arrows + (arrows-per-level * enchant-level) = total number of arrows
  arrows-per-level: 0
  # Flat damage multiplier on shotgun shots
  damage-multiplier: 2.0

decapitator:
  # Chance to drop head on decapitation
  drop-chance: 0.5

double-catch:
  chance-per-level: 0.1

nourish:
  amount-per-level: 1

syphon:
  health-per-level: 0.25
  chance-per-level: 0.05