name: RedEnchants
version: '${version}'
main: me.duro.redenchants.RedEnchants
api-version: '1.18'
depend:
  - PlaceholderAPI
  - Citizens

commands:
  redenchants:
    description: RedEnchants Command
    aliases: [re]
  souls:
    description: Souls Command
  horde:
    description: Horde Command